### ISSUE TITLE
rule/duplicate rule returns false positive when running pint as sidecar in prometheus

### ISSUE THREAD

**Issue by sambitD007** [cloudflare/pint#920] opened 2024-03-20 09:46 UTC
When running  pint as sidecar in prometheus  and it uses the same prometheus server to validate for duplicate rules, then it returns all rules in the prometheus pod as duplicate.

**Comment by prymitive** [comment] 2024-03-21 11:43
What command did you run? What's your config?

**Comment by sambitD007** [comment] 2024-03-21 11:58
@prymitive I am loading config  as configmap
Below is the configmap
`apiVersion: v1
data:
  .pint.hcl: |
    parser {
      relaxed = [ "(.*)" ]
    }
    checks {
      disabled = ["promql/regexp","alerts/template","promql/series","rule/duplicate"]
    }
    prometheus "pint-prometheus-0" {
      uri         = "http://localhost:9090"
      concurrency = 20
      tls {
        skipVerify = true
      }
    }
kind: ConfigMap`

And the pint container configuration are as below
`- args:
    - --config
    - /pint-configmap/.pint.hcl
    - watch
    - --listen
    - :8082
    - /etc/prometheus/rules
    command:
    - pint
    image: xxxxxxxxx.amazonaws.com/common/pint:0.53.0
    imagePullPolicy: IfNotPresent
    name: pint-container
    ports:
    - containerPort: 8082
      protocol: TCP
    resources:
      limits:
        cpu: 512m
        memory: 750Mi
      requests:
        cpu: 256m
        memory: 500Mi
    volumeMounts:
    - mountPath: /pint-configmap
      name: pint-configmap
    - mountPath: /etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-0
      name: prometheus-kube-prometheus-rulefiles-0
    - mountPath: /etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-1
      name: prometheus-kube-prometheus-rulefiles-1
    - mountPath: /etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-2
      name: prometheus-kube-prometheus-rulefiles-2
    - mountPath: /etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-3
      name: prometheus-kube-prometheus-rulefiles-3`

**Comment by prymitive** [comment] 2024-03-21 12:19
Can't reproduce this locally, maybe you do have duplicated rules in your files?

**Comment by sambitD007** [comment] 2024-03-21 15:00
@prymitive  Are you using exactly the same args and config as above? I have checked and double checked. It might be related to getting duplicate pint_problem. When running on sidecar I am getting duplicate pint_problem for the same problem with different paths
Eg:
```
pint_problem{container="pint-container", endpoint="8082", filename="/etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-1/..2024_03_19_14_15_35.3805314834/dev-3p-staging-monitoring-service-navi-service-3b65ff61-6efd-41aa-9388-993c43f70fc7.yaml", instance="10.5.20.19:8082", job="prometheus-kube-prometheus", kind="alerting", name="Test Alert", namespace="monitoring", pod="prometheus-kube-prometheus-1", problem="`rate()` should only be used with counters but `camunda_process_incidents_total` is a gauge according to metrics metadata from `pint-prometheus-0` Prometheus server at http://localhost:9090.", reporter="promql/rate", service="prometheus-kube-prometheus", serviceName="dev-", severity="bug"}
pint_problem{container="pint-container", endpoint="8082", filename="/etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-1/..2024_03_19_14_16_18.2655305935/dev-3p-staging-monitoring-service-navi-service-3b65ff61-6efd-41aa-9388-993c43f70fc7.yaml", instance="10.5.46.183:8082", job="prometheus-kube-prometheus", kind="alerting", name="Test Alert", namespace="monitoring", pod="prometheus-kube-prometheus-0", problem="`rate()` should only be used with counters but `camunda_process_incidents_total` is a gauge according to metrics metadata from `pint-prometheus-0` Prometheus server at http://localhost:9090.", reporter="promql/rate", service="prometheus-kube-prometheus", serviceName="dev-", severity="bug"}
``` 
The path of file is /prometheus-kube-prometheus-rulefiles-1/dev-3p-staging-monitoring-service-navi-service-3b65ff61-6efd-41aa-9388-993c43f70fc7.yaml but 2 different intermediate paths are getting added

**Comment by prymitive** [comment] 2024-03-21 15:16
I'm confused.
Ticket title says `rule/duplicate rule returns false positive` but you're pasting a problem reported by `reporter="promql/rate"`, there are two instances of that `pint_problem` because there are two different `instance` labels, so this seems to be coming from two different pint instances. That's not a problem with pint, that's most likely because you scrape pint twice. 
Can you please paste `rule/duplicate` report that's invalid?

**Comment by sambitD007** [comment] 2024-03-22 14:30
@prymitive  My apologies for causing confusion. In any case sharing the alert and the respective prometheus recording rule.

```
pint_problem{container="pint-container", endpoint="8082", filename="/etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-0/..2024_03_22_10_35_59.2359295599/logging-fluentd-alertrules-befc54ad-2893-4602-8021-c1f4f45af61f.yaml", instance="10.8.34.135:8082", job="prometheus-kube-prometheus", kind="recording", name="fluentd_input_status_num_records_total:rate5m", namespace="monitoring", pod="prometheus-kube-prometheus-0", problem="Duplicated rule, identical rule found at /etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-0/..2024_03_22_10_35_59.2359295599/logging-fluentd-alertrules-befc54ad-2893-4602-8021-c1f4f45af61f.yaml:6.", reporter="rule/duplicate", service="prometheus-kube-prometheus", service_name="logging-fluentd-alertrules-befc", severity="bug"}
```
The corresponding recording rule
```
- interval: 5m
  name: fluentd-recording
  rules:
  - expr: sum by (service_name) (rate(fluentd_input_status_num_records_total{service_name!~'gocd-agent-container.*'}[5m]))
    record: fluentd_input_status_num_records_total:rate5m
```

**Comment by prymitive** [comment] 2024-03-22 15:02
Do you get the same with latest pint version?
I've just noticed that you're using `pint:0.53.0`, that's a few releases behind, and there were some fixes for rule/duplicate on https://github.com/cloudflare/pint/blob/main/docs/changelog.md

**Comment by sambitD007** [comment] 2024-03-28 17:26
I tried with latest version with single pod yet the same result.

**Comment by prymitive** [comment] 2024-04-02 13:27
This is probably not a problem with pint but with how your k8s environment manages rules.
Looking at this again I see that these filenames are identical *except* for included timestaps: `2024_03_19_14_15_35.3805314834` vs `2024_03_19_14_16_18.2655305935`

```
filename="/etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-1/..2024_03_19_14_15_35.3805314834/dev-staging-monitoring-service-3b65ff61-6efd-41aa-9388-993c43f70fc7.yaml", 
filename="/etc/prometheus/rules/prometheus-kube-prometheus-rulefiles-1/..2024_03_19_14_16_18.2655305935/dev-staging-monitoring-service-3b65ff61-6efd-41aa-9388-993c43f70fc7.yaml",
```

So I'm going to hazard a guess that this two files are the same thing, just deployed at two different times. Maybe it writes new rules and then updates paths in Prometheus config (?), leaving some old files behind.
If so this is not a bug in pint but just how your Prometheus rule deployment behaves in k8s. I'm closing this, feel free to re-open if you manage to reproduce it outside of k8s, I can't.

If you can use [pint watch rule_files http://...](https://cloudflare.github.io/pint/#watch-mode) instead of `pint watch glob` then that might solve this for you.

**Closed by prymitive** 2024-04-02 13:27 UTC

**Comment by sambitD007** [comment] 2024-04-02 18:55
I actually missed to mention this but I have also tried the combination you have provided earlier
```
 - args:
    - --config
    - /pint-configmap/.pint.hcl
    - watch
    - --listen
    - :8082
    - rule_files
    - pint-prometheus-0
```
